### ISSUE TITLE
Contributing to Ryal

### ISSUE THREAD

**Issue by marjaimate** [ryal/ryal#4]
Hi Ben, I'm happy to take part in the project. LMK what's needed :smile_cat:

**Comment by BenMorganIO** [comment]
Hey @marjaimate,

If you're interested, I've got https://github.com/ryal/ryal/issues/13 which I think would be right up your alley :)

**Comment by BenMorganIO** [comment]
I've got #14 up and I'm going to be moving from PaymentMethods soon to thinking about the Payment State Machine. When the state machine is up, I think you and @James-Byrne should have a look through. At that point, there'll probably be a lot more work to come after that with ensuring Stripe and friends are all playing nice together.

**Comment by marjaimate** [comment]
Great stuff. I'll take a look later today / tomorrow.
